version: '3.8'
services:
  clickhouse:
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    image: clickhouse/clickhouse-server:23.9.3.12-alpine
    container_name: clickhouse
    hostname: clickhouse
    volumes:
      - ${PWD}/fs/volumes/clickhouse/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ${PWD}/fs/volumes/clickhouse/var/lib/clickhouse/:/var/lib/clickhouse/
      - ${PWD}/fs/volumes/clickhouse/var/log/clickhouse-server/:/var/log/clickhouse-server/
    ports:
      - "8123:8123"
      - "9000:9000"